# Generated by Django 5.0.1 on 2024-01-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('book_name', models.CharField(max_length=100)),
                ('book_price', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('balace', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
