# Generated by Django 5.0.1 on 2024-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_borrowingdatamodel_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingdatamodel',
            name='book_price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
