# Generated by Django 5.0.1 on 2024-01-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_alter_useraccount_user'),
        ('posts', '0007_post_price_alter_post_author_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingdatamodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_data', to='posts.post'),
        ),
    ]
